import { StyleSheet } from '@react-pdf/renderer'

const COLORS = {
  ink: '#1C1611',
  inkSoft: '#5C5142',
  gold: '#A8702E',
  goldAccent: '#B8922F',
  paper: '#FEFBF2',
  paperSoft: '#FBF5E4',
  divider: '#D9CFB8',
  border: '#E4D9BE',
  dark: '#1C1611',
  darkText: '#F8F1E0',
  darkGold: '#F5D48A',
}

export const cs = StyleSheet.create({
  page: {
    backgroundColor: COLORS.paper,
    paddingTop: 28,
    paddingBottom: 22,
    paddingHorizontal: 40,
    fontFamily: 'Inter',
    fontSize: 9.5,
    color: COLORS.ink,
    lineHeight: 1.42,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  sectionLabel: {
    fontSize: 8,
    color: COLORS.gold,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  title: {
    marginTop: 10,
    fontFamily: 'Playfair Display',
    fontSize: 28,
    fontWeight: 700,
    color: COLORS.ink,
    lineHeight: 1.02,
  },
  subtitle: {
    marginTop: 6,
    fontFamily: 'Playfair Display',
    fontSize: 12,
    fontStyle: 'italic',
    color: COLORS.inkSoft,
  },
  logoBlock: {
    alignItems: 'flex-end',
  },
  logo: {
    width: 62,
    height: 62,
    objectFit: 'contain',
  },
  logoUrl: {
    marginTop: 2,
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 1.2,
  },
  divider: {
    marginVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.goldAccent,
  },
  articleDivider: {
    marginTop: 10,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  sectionTitle: {
    fontFamily: 'Playfair Display',
    fontSize: 15,
    fontWeight: 700,
    fontStyle: 'italic',
    color: COLORS.ink,
    marginBottom: 5,
  },
  partiesRow: {
    flexDirection: 'row',
    gap: 16,
  },
  partyCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 11,
  },
  partyLine: {
    fontSize: 9.5,
    color: COLORS.ink,
    marginBottom: 2,
  },
  intro: {
    marginTop: 12,
    fontFamily: 'Playfair Display',
    fontSize: 10.5,
    fontStyle: 'italic',
    color: COLORS.inkSoft,
  },
  article: {
    marginTop: 10,
  },
  paragraph: {
    fontSize: 9.3,
    color: COLORS.ink,
    marginBottom: 3,
    lineHeight: 1.45,
  },
  bulletList: {
    marginTop: 2,
    marginLeft: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 2,
    gap: 6,
  },
  bulletDot: {
    width: 8,
    fontSize: 9.5,
    color: COLORS.gold,
  },
  bulletText: {
    flex: 1,
    fontSize: 9.3,
    color: COLORS.ink,
    lineHeight: 1.4,
  },
  priceCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 10,
  },
  choiceRow: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 12,
  },
  choiceBox: {
    flex: 1.45,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 10,
  },
  finalBox: {
    flex: 0.95,
    borderWidth: 1,
    borderColor: COLORS.goldAccent,
    backgroundColor: COLORS.dark,
    padding: 10,
  },
  finalPrice: {
    marginTop: 10,
    fontFamily: 'Playfair Display',
    fontSize: 20,
    fontWeight: 700,
    fontStyle: 'italic',
    color: COLORS.darkGold,
  },
  finalMeta: {
    marginTop: 4,
    fontSize: 9,
    color: COLORS.darkText,
    letterSpacing: 1.2,
  },
  finalSub: {
    marginTop: 8,
    fontSize: 9,
    color: '#D9CFB8',
  },
  noteBox: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 10,
  },
  serviceChip: {
    marginBottom: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paper,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  serviceName: {
    fontSize: 9.3,
    color: COLORS.ink,
    fontWeight: 700,
  },
  serviceMeta: {
    marginTop: 2,
    fontSize: 8.4,
    color: COLORS.inkSoft,
  },
  signatureRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 16,
  },
  signatureBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 10,
  },
  signatureHint: {
    fontSize: 8.5,
    color: COLORS.inkSoft,
    marginTop: 6,
  },
  signatureArea: {
    marginTop: 8,
    height: 44,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS.divider,
  },
  signatureDate: {
    marginTop: 8,
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    fontSize: 8.5,
    color: COLORS.inkSoft,
  },
  signatureImg: {
    marginTop: 6,
    width: 88,
    height: 38,
    objectFit: 'contain',
  },
  footer: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 1.1,
  },
  legalNote: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 0.8,
  },
})
