import { StyleSheet } from '@react-pdf/renderer'

const COLORS = {
  ink: '#1C1611',
  inkSoft: '#5C5142',
  gold: '#A8702E',
  goldAccent: '#B8922F',
  paper: '#FEFBF2',
  paperSoft: '#FBF5E4',
  divider: '#D9CFB8',
  border: '#E4D9BE',
  dark: '#1C1611',
  darkText: '#F8F1E0',
  darkGold: '#F5D48A',
}

export const cs = StyleSheet.create({
  page: {
    backgroundColor: COLORS.paper,
    paddingTop: 26,
    paddingBottom: 16,
    paddingHorizontal: 38,
    fontFamily: 'Inter',
    fontSize: 9.4,
    color: COLORS.ink,
    lineHeight: 1.48,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  sectionLabel: {
    fontSize: 8,
    color: COLORS.gold,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  title: {
    marginTop: 10,
    fontFamily: 'Playfair Display',
    fontSize: 31,
    fontWeight: 700,
    color: COLORS.ink,
    lineHeight: 1.02,
  },
  subtitle: {
    marginTop: 6,
    fontFamily: 'Playfair Display',
    fontSize: 11.5,
    fontStyle: 'italic',
    color: COLORS.inkSoft,
  },
  logoBlock: {
    alignItems: 'flex-end',
  },
  logo: {
    width: 62,
    height: 62,
    objectFit: 'contain',
  },
  logoUrl: {
    marginTop: 2,
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 1.2,
  },
  divider: {
    marginVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.goldAccent,
  },
  articleDivider: {
    marginTop: 6,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  sectionTitle: {
    fontFamily: 'Playfair Display',
    fontSize: 15.5,
    fontWeight: 700,
    fontStyle: 'italic',
    color: COLORS.ink,
    marginBottom: 5,
  },
  sectionTitleCompact: {
    fontFamily: 'Playfair Display',
    fontSize: 14.5,
    fontWeight: 700,
    fontStyle: 'italic',
    color: COLORS.ink,
    marginBottom: 4,
    backgroundColor: COLORS.paper,
    paddingRight: 8,
    alignSelf: 'flex-start',
  },
  partiesRow: {
    flexDirection: 'row',
    gap: 16,
  },
  partyCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 11,
  },
  partyLine: {
    fontSize: 9.5,
    color: COLORS.ink,
    marginBottom: 2,
  },
  intro: {
    marginTop: 12,
    fontFamily: 'Playfair Display',
    fontSize: 10,
    fontStyle: 'italic',
    color: COLORS.inkSoft,
  },
  article: {
    marginTop: 8,
  },
  articleCompact: {
    marginTop: 4,
  },
  pageBottomBlock: {
    position: 'absolute',
    left: 38,
    right: 38,
    bottom: 0,
  },
  paragraph: {
    fontSize: 8.8,
    color: COLORS.ink,
    marginBottom: 2,
    lineHeight: 1.36,
  },
  paragraphCompact: {
    fontSize: 8.1,
    color: COLORS.ink,
    marginBottom: 1,
    lineHeight: 1.28,
  },
  bulletList: {
    marginTop: 2,
    marginLeft: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 1,
    gap: 6,
  },
  bulletDot: {
    width: 8,
    fontSize: 9.5,
    color: COLORS.gold,
  },
  bulletText: {
    flex: 1,
    fontSize: 8.8,
    color: COLORS.ink,
    lineHeight: 1.32,
  },
  priceCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paper,
    padding: 0,
  },
  priceHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4ECD6',
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  priceRow: {
    flexDirection: 'row',
    paddingVertical: 2,
    paddingHorizontal: 12,
  },
  priceNumeral: {
    width: 30,
    fontFamily: 'Playfair Display',
    fontSize: 11,
    fontStyle: 'italic',
    fontWeight: 700,
    color: COLORS.gold,
  },
  priceDesignation: {
    flex: 1,
    paddingRight: 12,
  },
  priceTitle: {
    fontSize: 8.4,
    fontWeight: 700,
    color: COLORS.ink,
  },
  priceDescription: {
    marginTop: 1,
    fontSize: 6.5,
    fontStyle: 'italic',
    color: COLORS.inkSoft,
  },
  priceMonth: {
    width: 74,
    fontSize: 7.8,
    textAlign: 'right',
    color: COLORS.ink,
  },
  priceYear: {
    width: 74,
    fontSize: 8.2,
    fontWeight: 700,
    textAlign: 'right',
    color: COLORS.ink,
  },
  choiceRow: {
    marginTop: 2,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  choiceBox: {
    flex: 1.45,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 6,
  },
  finalBox: {
    flex: 0.95,
    borderWidth: 1,
    borderColor: COLORS.goldAccent,
    backgroundColor: COLORS.dark,
    padding: 6,
    alignSelf: 'flex-start',
  },
  finalPrice: {
    marginTop: 6,
    fontFamily: 'Playfair Display',
    fontSize: 16,
    fontWeight: 700,
    fontStyle: 'italic',
    color: COLORS.darkGold,
  },
  finalMeta: {
    marginTop: 4,
    fontSize: 8.2,
    color: COLORS.darkText,
    letterSpacing: 1.2,
  },
  finalSub: {
    marginTop: 6,
    fontSize: 8.5,
    color: '#D9CFB8',
  },
  noteBox: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 5,
  },
  serviceChip: {
    marginBottom: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paper,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  serviceName: {
    fontSize: 8.8,
    color: COLORS.ink,
    fontWeight: 700,
  },
  serviceMeta: {
    marginTop: 1,
    fontSize: 7.4,
    color: COLORS.inkSoft,
  },
  signatureRow: {
    marginTop: 6,
    flexDirection: 'row',
    gap: 8,
  },
  signatureBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.paperSoft,
    padding: 6,
  },
  signatureHint: {
    fontSize: 7.5,
    color: COLORS.inkSoft,
    marginTop: 4,
  },
  signatureArea: {
    marginTop: 4,
    height: 18,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS.divider,
  },
  signatureDate: {
    marginTop: 4,
    paddingTop: 3,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    fontSize: 8.5,
    color: COLORS.inkSoft,
  },
  signatureImg: {
    marginTop: 2,
    width: 56,
    height: 20,
    objectFit: 'contain',
  },
  footer: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingTop: 6,
  },
  footerText: {
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 1.1,
  },
  legalNote: {
    marginTop: 2,
    textAlign: 'center',
    fontSize: 8,
    color: COLORS.inkSoft,
    letterSpacing: 0.8,
  },
})
